
label Act_1:

    jump .day_1

label .day_1:

    "Es un día habitual en el club."
    "Llevo mi libro favorito en mis manos, aquel que leía desde que era una niña."
    "La literatura y yo tenemos una conexión especial."
    "Desde siempre me interesaron los libros."
    "Devoro libros como pastelillos, con mi taza de té a lado."
    "Noto como [player] me observa. ¿Qué es lo que necesita?"
    mc "¡Yuri!"
    y "¡Ah! ¿S-sí?"
    mc "Ese libro que tienes parece interesante."
    mc "¿Y si lo leemos juntos?"
    mc "Ya ha pasado un buen tiempo desde que no leemos algo tu y yo."
    y "¡N-no!"
    "..."
    y "Q-quiero decir, no se si te guste."
    y "El libro es un poco aburrido."
    mc "¿Qué?"
    mc "Jaja, no te preocupes Yuri... se que no es como el manga pero ya me acostumbre a leer por el club."
    y "B-bueno supongo que podría prestártelo si insistes tanto."
    "Tímidamente entrego el libro en las manos de [player]."
    mc "Lo leeré con clama en casa."
    mc "¡Hasta luego Yuri!"
    "Y así termina el día."
    "..."
    "Solo espero que no lea las viejas notas de mi libro."
    jump .day_2

label .day_2:

    mc "¡Hey Yuri!"
    y "¿S-sí?"
    mc "Tu libro esta muy interesante..."
    mc "Quiero terminarlo, pero te lo devuelvo por hoy ya que vi extrañas anotaciones sobre la historia."
    mc "¡Y puse también las mías!"
    y "¡Q-qué!"
    mc "Así es."
    "[player] se aparta, va a saludar a los otros integrantes."
    "Con duda abro mi libro, en una página puedo ver una nota que responde a la mía."
    "..."
    "Mi nota dice:"
    "'La amistad no es posible para la gente que es extremadamente tímida.'"
    "La de él responde:"
    "'Vaya Yuri... creo que eso es muy duro para esas personas ¿no crees?'"
    "..."
    "Rápidamente cierro el libro."
    "Mis mejillas se ruborizan y mi corazón empieza a latir fuertemente."
    "{i}Q-que vergüenza...{/i}"
    "Por instinto vuelvo abrir el libro y respondo a la anotación de [player]."
    "'...Bueno simplemente creo que así es como es.'"
    "'La chica de la novela no puede relacionarse, es tímida, frágil, seria... aburrida.'"
    "'¿A ti te llamaría la atención una chica así?'"
    "Cierro el libro nuevamente y por detrás con mi dedo toco suavemente la espala de [player]."
    y "E-eh... ten, léelo cuando estés en casa."
    "[player] me sonríe,  haciendo que mi rubor se haga más evidente..."
    "Pero ya no hay vuelta atrás."
    "[Sayori]"
    "asdadsad"